"""Add colegio to User

Revision ID: 3a7893c001f6
Revises: a104da6eae6b
Create Date: 2025-08-07 09:37:39.849992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7893c001f6'
down_revision = 'a104da6eae6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colegio', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('colegio')

    # ### end Alembic commands ###
